server:
  port: 8084
spring:
  application:
    name: "Catalyst"
  datasource:
    url: "jdbc:mariadb://localhost:3306/Catalyst"
    username: "admin"
    password: "admin"
    driver-class-name: org.mariadb.jdbc.Driver
  profiles:
    active: "prod"
